Locale.nl = {
	AlreadyWearing = "Dat draagt u al.",
	Bag = "Tas",
	Bag2 = "Opent of sluit je tas.",
	Bracelet = "Armband",
	Ear = "Oor",
	Ear2 = "Oor accessoire",
	Glasses = "Glasses",
	Gloves = "Handschoenen",
	Hair = "Haar",
	Hair2 = "Doe je haar omhoog/omlaag/in een knot/paardenstaart.",
	Hat = "Hoed",
	Info = "Informatie",
	Information = "Als de knop blauw is, heb je een opgeslagen item.",
	Mask = "Masker",
	Neck = "Nek",
	Neck2 = "Nek accessoire",
	NotAllowedPed = "Dit ped-model staat deze optie niet toe.",
	NothingToRemove = "U lijkt niets te verwijderen.",
	NoVariants = "Hier lijken geen varianten voor te bestaan.",
	Pants = "Broek",
	PleaseWait = "Even geduld aub...",
	Shirt = "Shirt",
	Shoes = "Schoenen",
	TakeOffOn = "Zet je %s uit/aan.",
	Top = "Bovenkant",
	Top2 = "Toggle overhemd variatie.",
	Vest = "Vest",
	Visor = "Vizier",
	Visor2 = "Toggle hoed variatie.",
	Watch = "Horloge",
	NoShirtOn = "Je kunt dit niet doen zonder je shirt aan.",
	Reset = "Terugdraaien",
	Reset2 = "Zet alles weer normaal.",
	Exit = "Sluit",
	-- Commands
	BAG = "tas",
	BRACELET = "armband",
	EAR = "oor",
	GLASSES = "bril",
	GLOVES = "handschoenen",
	HAIR = "haar",
	HAT = "hoed",
	MASK = "masker",
	NECK = "nek",
	SHOES = "schoenen",
	TOP = "bovenkant",
	VEST = "vest",
	VISOR = "vizier",
	WATCH = "horloge",
	PANTS = "broek",
	SHIRT = "shirt",
	RESET = "revertkleding",
	BAGOFF = "tasuit",
}

-- Created by Niels C.
-- Discord: Niels™#4636
